Layout/IndentationWidth:
  Width: 4

Metrics/AbcSize:
  Max: 50

Metrics/LineLength:
  Max: 180

Metrics/BlockLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength: 
  Max: 60

Metrics/PerceivedComplexity:
  Max: 20

Style/GlobalVars:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/WordArray:
  EnforcedStyle: brackets

